baseURL: ""
languageCode: en-us
title: Demo for Hugo
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10

    - identifier: tags
      name: Tagssss
      url: /tags/
      weight: 20

    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
      